/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/quote-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createQuoteRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        QuoteRequest: {
            /** Format: uuid */
            requestId: string;
            subject: string | null;
            /** Format: date-time */
            approvedAt: string;
            fields: {
                company: string | null;
                contactPerson: string | null;
                /** @description ISO date (YYYY-MM-DD) when the value is a date, else the reviewed text. */
                requestedDeliveryDate: string | null;
            };
        };
        QuoteRequestReceipt: {
            erpReference: string;
            /** Format: uuid */
            requestId: string;
            /** Format: date-time */
            receivedAt: string;
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "invalid_request" | "unauthorized" | "idempotency_conflict" | "unavailable";
                message: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createQuoteRequest: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            /** @description Replay – the key was seen before; same reference as the first call. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteRequestReceipt"];
                };
            };
            /** @description Created – the ERP stored the quote request. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteRequestReceipt"];
                };
            };
            /** @description Invalid body or missing/invalid Idempotency-Key. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing or wrong bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The key was used before with a different body. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Temporarily unavailable – retry with the same key. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
