-- Generated by drizzle-kit; edited: the UNIQUE (id, company_id) must exist before the FKs that use it.
ALTER TABLE "app"."documents" DROP CONSTRAINT "documents_request_id_requests_id_fk";
--> statement-breakpoint
ALTER TABLE "app"."requests" DROP CONSTRAINT "requests_duplicate_of_id_requests_id_fk";
--> statement-breakpoint
ALTER TABLE "app"."requests" ADD CONSTRAINT "requests_id_company_unique" UNIQUE("id","company_id");--> statement-breakpoint
ALTER TABLE "app"."documents" ADD CONSTRAINT "documents_request_same_company_fk" FOREIGN KEY ("request_id","company_id") REFERENCES "app"."requests"("id","company_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."requests" ADD CONSTRAINT "requests_duplicate_same_company_fk" FOREIGN KEY ("duplicate_of_id","company_id") REFERENCES "app"."requests"("id","company_id") ON DELETE no action ON UPDATE no action;
