/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse one document, extract header fields and line items, verify every quote. */
        post: operations["extract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttachmentRef */
        AttachmentRef: {
            /**
             * Index
             * @description 0-based position among the message's attachments.
             */
            index: number;
            /**
             * Name
             * @description File name as stored in the message (untrusted text).
             */
            name: string | null;
        };
        /**
         * AttachmentResult
         * @description One attachment of an Outlook ``.msg`` (also nested ones), parsed or not.
         */
        AttachmentResult: {
            /**
             * Path
             * @description 0-based attachment index per nesting level, outermost first; the last one is `attachment.index` in the locators of this attachment's segments.
             */
            path: number[];
            /**
             * Name
             * @description File name as stored in the message (untrusted text).
             */
            name: string | null;
            /**
             * Documentkind
             * @description Detected kind; null when failed.
             */
            documentKind: ("pdf" | "eml" | "xlsx" | "docx" | "msg") | null;
            /**
             * Status
             * @enum {string}
             */
            status: "parsed" | "failed";
            /**
             * Error
             * @description Why the attachment was not parsed; null when parsed. The message and its other attachments are still processed.
             */
            error: ("unsupported_media_type" | "document_unparseable" | "document_too_long" | "nesting_too_deep" | "too_many_attachments" | "not_attached_by_value") | null;
            /**
             * Segmentcount
             * @description Segments this attachment contributed.
             */
            segmentCount: number;
        };
        /**
         * BoundingBox
         * @description Box in PDF points; origin top-left of the page (``t`` < ``b``).
         */
        BoundingBox: {
            /** L */
            l: number;
            /** T */
            t: number;
            /** R */
            r: number;
            /** B */
            b: number;
        };
        /**
         * DocxLocator
         * @description A body paragraph (``part=paragraph``) or one table cell (``part=table_cell``).
         */
        DocxLocator: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "docx";
            /**
             * Part
             * @enum {string}
             */
            part: "paragraph" | "table_cell";
            /**
             * Paragraph
             * @description 1-based index of the paragraph among the body paragraphs (empty ones count); null for a table cell.
             */
            paragraph: number | null;
            /**
             * Table
             * @description 1-based table index in the body.
             */
            table: number | null;
            /**
             * Row
             * @description 1-based row in the table.
             */
            row: number | null;
            /**
             * Cell
             * @description 1-based grid column where the cell starts (a merged cell counts once).
             */
            cell: number | null;
        };
        /** EmailLocator */
        EmailLocator: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "email";
            /**
             * Part
             * @enum {string}
             */
            part: "header" | "body";
            /**
             * Line
             * @description 1-based line in the decoded text body (part=body), or 1-based position in the header list (part=header).
             */
            line: number;
            /**
             * Header
             * @description Header name when part=header.
             */
            header: string | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /**
             * Code
             * @enum {string}
             */
            code: "invalid_request" | "unauthorized" | "length_required" | "document_too_large" | "unsupported_media_type" | "document_unparseable" | "document_too_long" | "busy" | "model_error" | "model_output_invalid" | "internal_error";
            /**
             * Message
             * @description Short, fixed text. Never contains document content.
             */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
            /** Requestid */
            requestId: string | null;
        };
        /** Evidence */
        Evidence: {
            /**
             * Segmentid
             * @description Id of a segment in `segments`.
             */
            segmentId: string;
            /**
             * Quote
             * @description Text the model copied from that segment.
             */
            quote: string;
        };
        /** ExtractRequest */
        ExtractRequest: {
            /**
             * File
             * @description The document bytes: PDF, .eml, Outlook .msg, .docx/.docm or .xlsx/.xlsm. The kind is detected from the bytes, not from the file name.
             */
            file: string;
            /**
             * Documentid
             * @description Opaque ID from the caller; echoed and logged, never interpreted.
             */
            documentId: string;
            /**
             * Mediatype
             * @description Declared media type, e.g. message/rfc822. Only helps to recognise an .eml; every kind is detected from the bytes.
             */
            mediaType?: string | null;
        };
        /** ExtractResponse */
        ExtractResponse: {
            /** Requestid */
            requestId: string;
            /** Documentid */
            documentId: string;
            /**
             * Documentkind
             * @description Detected from the bytes: pdf, eml, xlsx, docx or msg (Outlook).
             * @enum {string}
             */
            documentKind: "pdf" | "eml" | "xlsx" | "docx" | "msg";
            /** Segments */
            segments: components["schemas"]["Segment"][];
            fields: components["schemas"]["ExtractedFields"];
            /**
             * Lineitems
             * @description Requested positions in document order (schemaVersion 2); empty when none.
             */
            lineItems: components["schemas"]["LineItem"][];
            run: components["schemas"]["RunMetadata"];
            /**
             * Warnings
             * @description `no_text`: the document has no text (e.g. a scan without OCR); no model call made. `attachment_failed`: at least one attachment of a `.msg` could not be parsed (see `attachments`); the rest was processed.
             */
            warnings: ("no_text" | "attachment_failed")[];
            /**
             * Attachments
             * @description Attachments of an Outlook `.msg`, flattened in document order (nested ones after their parent); empty for other kinds.
             */
            attachments?: components["schemas"]["AttachmentResult"][];
        };
        /**
         * ExtractedFields
         * @description Field keys are fixed snake_case identifiers shared with the TS side.
         */
        ExtractedFields: {
            /** @description Requesting company; trimmed text. */
            company: components["schemas"]["FieldResult"];
            /** @description Contact person; trimmed text. */
            contact_person: components["schemas"]["FieldResult"];
            /** @description Requester's e-mail address; lowercased. */
            email: components["schemas"]["FieldResult"];
            /** @description Requester's phone number; trimmed as written, no country code added. */
            phone: components["schemas"]["FieldResult"];
            /** @description Requested delivery date as YYYY-MM-DD; a calendar week without a date is at most `uncertain` (reason `calendar_week_only`, value `KW 42` or `KW 42/2026`). */
            requested_delivery_date: components["schemas"]["FieldResult"];
            /** @description Additional requirements (certificates, tolerances, ...); trimmed text. */
            additional_requirements: components["schemas"]["FieldResult"];
        };
        /** FieldResult */
        FieldResult: {
            /**
             * Value
             * @description Extracted value. For `found` and verified `uncertain` it is normalised: trimmed text; dates as YYYY-MM-DD (a calendar week without a date stays a week, see `reason` `calendar_week_only`); quantities as a plain decimal with a dot and no grouping ("1250", "2.5"); units canonical (mm, cm, m, kg, t, pcs) or trimmed text for other units; e-mail lowercased; phone trimmed as written (no country code added). Kept as the model sent it for `unverified` (and for `uncertain` without evidence) so a human can review the proposal; null for `missing`.
             */
            value: string | null;
            /**
             * Status
             * @description Final status after verification. `found` only if the verifier confirmed the quote in the cited segment and the value against the quote.
             * @enum {string}
             */
            status: "found" | "uncertain" | "missing" | "unverified";
            evidence: components["schemas"]["Evidence"] | null;
            /**
             * Modelstatus
             * @description What the model claimed before verification.
             * @enum {string}
             */
            modelStatus: "found" | "uncertain" | "missing";
            /**
             * Reason
             * @description Why the verifier set `unverified`; for `uncertain`: `ambiguous_quote` when it downgraded `found` (the quote holds several dates), `calendar_week_only` when a date field only has a calendar week (value then `KW <week>` or `KW <week>/<year>`, never a computed date) or `ocr_only` when the only evidence is OCR text (a segment with `locator.ocr`, also inside an attachment); null otherwise.
             */
            reason: ("missing_with_value" | "no_value" | "no_evidence" | "unknown_segment" | "empty_quote" | "quote_not_in_segment" | "value_not_in_quote" | "ambiguous_quote" | "calendar_week_only" | "ocr_only") | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * LineItem
         * @description One requested position; every field is verified on its own (same rules as header fields).
         */
        LineItem: {
            /**
             * Index
             * @description 0-based position in the document order.
             */
            index: number;
            /** @description Product or article; trimmed text. */
            description: components["schemas"]["FieldResult"];
            /** @description Quantity as a plain decimal with a dot and no grouping ("1250", "2.5"). */
            quantity: components["schemas"]["FieldResult"];
            /** @description Unit: one of mm, cm, m, kg, t, pcs (Stk., St., Stueck -> pcs) when known; otherwise the unit as written, trimmed. */
            unit: components["schemas"]["FieldResult"];
            /** @description Material or material number; trimmed text. */
            material: components["schemas"]["FieldResult"];
            /** @description Dimensions or nominal size; trimmed text. */
            dimensions: components["schemas"]["FieldResult"];
        };
        /**
         * MsgLocator
         * @description Outlook ``.msg``: headers and body lines like ``email``; attachments wrap their locator.
         */
        MsgLocator: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "msg";
            /**
             * Part
             * @enum {string}
             */
            part: "header" | "body" | "attachment";
            /**
             * Line
             * @description 1-based line in the decoded text body (part=body), or 1-based position in the header list (part=header); null for part=attachment.
             */
            line: number | null;
            /**
             * Header
             * @description Header name when part=header.
             */
            header: string | null;
            /** @description The attachment holding the segment when part=attachment. */
            attachment: components["schemas"]["AttachmentRef"] | null;
            /**
             * Inner
             * @description Locator inside the attachment (pdf, xlsx, docx, email or a nested msg) when part=attachment.
             */
            inner: (components["schemas"]["PdfLocator"] | components["schemas"]["EmailLocator"] | components["schemas"]["XlsxLocator"] | components["schemas"]["DocxLocator"] | components["schemas"]["MsgLocator"]) | null;
        };
        /** PdfLocator */
        PdfLocator: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "pdf";
            /**
             * Page
             * @description 1-based page number.
             */
            page: number;
            bbox: components["schemas"]["BoundingBox"];
            /**
             * Coordorigin
             * @default TOPLEFT
             * @constant
             */
            coordOrigin: "TOPLEFT";
            /**
             * Ocr
             * @description True when the text comes from OCR of a page without a text layer. A field whose evidence is OCR text is at most `uncertain` (reason `ocr_only`). Optional: absent means false.
             * @default false
             */
            ocr: boolean;
        };
        /** RunMetadata */
        RunMetadata: {
            /** Modelid */
            modelId: string;
            /**
             * Modelversion
             * @description Model version reported by the provider.
             */
            modelVersion: string | null;
            /** Promptversion */
            promptVersion: string;
            /** Schemaversion */
            schemaVersion: string;
            /**
             * Pdfpipeline
             * @description PDF pipeline used; null when no PDF was parsed (neither the document nor one of its attachments).
             */
            pdfPipeline: ("textlines" | "layout") | null;
            tokens: components["schemas"]["TokenUsage"];
            /**
             * Latencyms
             * @description Server-side time for parse + extract + verify.
             */
            latencyMs: number;
            /**
             * Modellatencyms
             * @description Time of the model call; null if skipped.
             */
            modelLatencyMs: number | null;
        };
        /** Segment */
        Segment: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Locator */
            locator: components["schemas"]["PdfLocator"] | components["schemas"]["EmailLocator"] | components["schemas"]["XlsxLocator"] | components["schemas"]["DocxLocator"] | components["schemas"]["MsgLocator"];
        };
        /** TokenUsage */
        TokenUsage: {
            /** Inputtokens */
            inputTokens: number | null;
            /** Outputtokens */
            outputTokens: number | null;
            /** Totaltokens */
            totalTokens: number | null;
        };
        /**
         * XlsxLocator
         * @description One spreadsheet row: its non-empty cells are joined with `` | `` in the segment text.
         */
        XlsxLocator: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "xlsx";
            /**
             * Sheet
             * @description Sheet name as in the workbook.
             */
            sheet: string;
            /**
             * Row
             * @description 1-based row number.
             */
            row: number;
            /**
             * Cellrange
             * @description Range of the non-empty cells of the row, e.g. "A7:D7" (or "B7" for one cell).
             */
            cellRange: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    extract: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID, echoed in the response header and body and in logs. Must match ^[A-Za-z0-9._:-]{1,128}$; otherwise the service generates one. */
                "X-Request-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Invalid form fields. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid bearer token (checked before the body is read). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Content-Length header missing or not a number. */
            411: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Document larger than AI_MAX_DOCUMENT_BYTES (declared Content-Length checked before the body is read, the file size after). */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a PDF, RFC 5322 e-mail, Outlook .msg, DOCX or XLSX (e.g. legacy .doc/.xls, password-protected Office files, images). */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The document could not be parsed (`document_unparseable`) or is too long (`document_too_long`: more pages than AI_MAX_PDF_PAGES, too many rows, text blocks or pages without text to OCR). A failing attachment of a .msg does not cause this; it is reported in `attachments`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description All extraction slots busy; retry later. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The model call failed or returned invalid output; retry later. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
