/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse one document, extract header fields, verify every quote. */
        post: operations["extract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BoundingBox
         * @description Box in PDF points; origin top-left of the page (``t`` < ``b``).
         */
        BoundingBox: {
            /** L */
            l: number;
            /** T */
            t: number;
            /** R */
            r: number;
            /** B */
            b: number;
        };
        /** EmailLocator */
        EmailLocator: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "email";
            /**
             * Part
             * @enum {string}
             */
            part: "header" | "body";
            /**
             * Line
             * @description 1-based line in the decoded text body (part=body), or 1-based position in the header list (part=header).
             */
            line: number;
            /**
             * Header
             * @description Header name when part=header.
             */
            header: string | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /**
             * Code
             * @enum {string}
             */
            code: "invalid_request" | "unauthorized" | "document_too_large" | "unsupported_media_type" | "document_unparseable" | "busy" | "model_error" | "model_output_invalid" | "internal_error";
            /**
             * Message
             * @description Short, fixed text. Never contains document content.
             */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
            /** Requestid */
            requestId: string | null;
        };
        /** Evidence */
        Evidence: {
            /**
             * Segmentid
             * @description Id of a segment in `segments`.
             */
            segmentId: string;
            /**
             * Quote
             * @description Text the model copied from that segment.
             */
            quote: string;
        };
        /** ExtractRequest */
        ExtractRequest: {
            /**
             * File
             * @description The document bytes (PDF or .eml).
             */
            file: string;
            /**
             * Documentid
             * @description Opaque ID from the caller; echoed and logged, never interpreted.
             */
            documentId: string;
            /**
             * Mediatype
             * @description Declared media type, e.g. message/rfc822. PDF is detected from bytes.
             */
            mediaType?: string | null;
        };
        /** ExtractResponse */
        ExtractResponse: {
            /** Requestid */
            requestId: string;
            /** Documentid */
            documentId: string;
            /**
             * Documentkind
             * @enum {string}
             */
            documentKind: "pdf" | "eml";
            /** Segments */
            segments: components["schemas"]["Segment"][];
            fields: components["schemas"]["ExtractedFields"];
            run: components["schemas"]["RunMetadata"];
            /**
             * Warnings
             * @description `no_text`: the document has no text layer (e.g. a scan); no model call made.
             */
            warnings: "no_text"[];
        };
        /**
         * ExtractedFields
         * @description Field keys are fixed snake_case identifiers shared with the TS side.
         */
        ExtractedFields: {
            company: components["schemas"]["FieldResult"];
            contact_person: components["schemas"]["FieldResult"];
            requested_delivery_date: components["schemas"]["FieldResult"];
        };
        /** FieldResult */
        FieldResult: {
            /**
             * Value
             * @description Extracted value (dates as YYYY-MM-DD). Kept for `unverified` so a human can review the proposal; null for `missing`.
             */
            value: string | null;
            /**
             * Status
             * @description Final status after verification. `found` only if the verifier confirmed the quote in the cited segment and the value against the quote.
             * @enum {string}
             */
            status: "found" | "uncertain" | "missing" | "unverified";
            evidence: components["schemas"]["Evidence"] | null;
            /**
             * Modelstatus
             * @description What the model claimed before verification.
             * @enum {string}
             */
            modelStatus: "found" | "uncertain" | "missing";
            /**
             * Reason
             * @description Why the verifier set `unverified`; null otherwise.
             */
            reason: ("missing_with_value" | "no_value" | "no_evidence" | "unknown_segment" | "empty_quote" | "quote_not_in_segment" | "value_not_in_quote") | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** PdfLocator */
        PdfLocator: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "pdf";
            /**
             * Page
             * @description 1-based page number.
             */
            page: number;
            bbox: components["schemas"]["BoundingBox"];
            /**
             * Coordorigin
             * @default TOPLEFT
             * @constant
             */
            coordOrigin: "TOPLEFT";
        };
        /** RunMetadata */
        RunMetadata: {
            /** Modelid */
            modelId: string;
            /**
             * Modelversion
             * @description Model version reported by the provider.
             */
            modelVersion: string | null;
            /** Promptversion */
            promptVersion: string;
            /** Schemaversion */
            schemaVersion: string;
            /**
             * Pdfpipeline
             * @description PDF pipeline used; null for e-mails.
             */
            pdfPipeline: ("textlines" | "layout") | null;
            tokens: components["schemas"]["TokenUsage"];
            /**
             * Latencyms
             * @description Server-side time for parse + extract + verify.
             */
            latencyMs: number;
            /**
             * Modellatencyms
             * @description Time of the model call; null if skipped.
             */
            modelLatencyMs: number | null;
        };
        /** Segment */
        Segment: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Locator */
            locator: components["schemas"]["PdfLocator"] | components["schemas"]["EmailLocator"];
        };
        /** TokenUsage */
        TokenUsage: {
            /** Inputtokens */
            inputTokens: number | null;
            /** Outputtokens */
            outputTokens: number | null;
            /** Totaltokens */
            totalTokens: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    extract: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID, echoed in the response header and body and in logs. Must match ^[A-Za-z0-9._:-]{1,128}$; otherwise the service generates one. */
                "X-Request-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Invalid form fields. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Document larger than AI_MAX_DOCUMENT_BYTES. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a PDF or RFC 5322 e-mail (.msg is not supported yet). */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The document could not be parsed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description All extraction slots busy; retry later. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The model call failed or returned invalid output; retry later. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
